services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${DOCKERMINIOROOTUSER}
      - MINIO_ROOT_PASSWORD=${DOCKERMINIOROOTPASS}
    volumes:
      - ./minio/data:/data
    networks:
      - back-tier
    command: server --console-address ":9001" /data

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - back-tier

  app:
    build: .
    container_name: go-app
    depends_on:
      - db
    environment:
      DB_USER: "root"
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_CHARSET: ${DB_CHARSET}
      DB_PARSE_TIME: ${DB_PARSE_TIME}
      DB_LOC: ${DB_LOC}
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - back-tier
    command: ["./main"]

volumes:
  db_data:
networks:
  back-tier: {}